<?php

namespace AppBundle\Repository;

/**
 * FigurerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigurerRepository extends \Doctrine\ORM\EntityRepository
{
}
