<?php

namespace CoreBundle\Repository;

/**
 * CooperativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CooperativeRepository extends \Doctrine\ORM\EntityRepository
{
	public function choisirCoop($id=1)
  	{
    	$quer1 = $this->_em->createQuery('SELECT c, d FROM CoreBundle:Cooperative c JOIN CoreBundle:Departement d WHERE c.id = :id');
    	$quer1->setParameter('id', $id);

    	return $quer1->getResult();
  	}
}
