<?php

namespace CoreBundle\Repository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{
    public function departementParRegion()
    {
        $quer3 = $this->_em->createQuery('SELECT d, r FROM CoreBundle:Departement u JOIN CoreBundle:Region r ORDER BY d.id ASC');
        $quer3->getArrayResult();
    }
}