<?php

namespace CoreBundle\Repository;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * listeLignes permet de récupérer les lignes correspondantes à la livraison
     */
    public function listeLignes($livraison)
    {
        
        $quer9 = $this->_em->createQuery('SELECT l FROM CoreBundle:Lign_fourniture l WHERE l.livraison = :livraison');
        $quer9->setParameter('livraison', $livraison);

        return $quer9->getResult();
    }

    /**
     * livraisonsEnCours permet de récupérer les livraisons en cours d'enregistrement
     */
    public function livraisonsEnCours($etat)
    {
        
        $quer10 = $this->_em->createQuery('SELECT l FROM CoreBundle:Livraison l WHERE l.etatLiv = :etat');
        $quer10->setParameter('etat', $etat);

        return $quer10->getResult();
    }

    /**
     * livraisonsParCooperative permet de récupérer les livraisons 
     */
    public function livraisonsParCooperative($coop)
    {
        
        $quer11 = $this->_em->createQuery('SELECT l FROM CoreBundle:Livraison l JOIN l.membre m WHERE m.cooperative =:coop');
        $quer11->setParameter('coop', $coop);

        return $quer11->getResult();
    }

    /**
     * stockProduitsParCooperative permet de récupérer les produits provenant des livraisons d'une cooperative 
     */
    public function stockProduitsParCooperative($coop)
    {
        $quer12 = $this->_em->createQuery('
            SELECT i, p
            FROM CoreBundle:Image i JOIN i.produit p , CoreBundle:Lign_fourniture f, CoreBundle:Livraison l, CoreBundle:Membre m 
            WHERE i.altImg = p.nomPrd
                AND p = f.produit
                AND f.livraison = l
                AND l.membre = m
                AND m.cooperative = :coop');

        $quer12->setParameter('coop', $coop);

        return $quer12->getResult();
    }

    
}
