<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * Union_coopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Union_coopRepository extends EntityRepository
{
  public function choisirUnion($id=1)
  {
    $quer1 = $this->_em->createQuery('SELECT u, i FROM CoreBundle:Union_coop u JOIN CoreBundle:Image i WHERE u.id = :id');
    $quer1->setParameter('id', $id);

    return $quer1->getResult();
  }

  public function recupererContactUnion($sigle="USCAEP")
  {
    $quer2 = $this->_em->createQuery('SELECT u.nomUn, u.sigleUn, u.siegeUn, u.telUn, u.eMailUn, u.heurUn, u.lnkFbUn FROM CoreBundle:Union_coop u WHERE u.sigleUn = :sigle');
    $quer2->setParameter('sigle', $sigle);

    return $quer2->getSingleResult();
  }
}
